postgres:
  image: postgres:12
  environment:
    - POSTGRES_PASSWORD=admin
    - POSTGRES_USER=admin
  ports:
    - "5432:5432"
  volumes:
    - ./lokalutvikling/postgres-init:/docker-entrypoint-initdb.d/
  container_name: postgres