application:
   name: familie-ef-iverksett
server:
   servlet:
      context-path: /
spring:
   main:
      allow-bean-definition-overriding: true
   flyway:
      enabled: true
   datasource:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/familie-ef-iverksett
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      hikari:
         maximum-pool-size: 5
         connection-test-query: "select 1"
         max-lifetime: 30000
         minimum-idle: 1
   application:
      name: iverksett
   jackson:
      mapper:
         accept-case-insensitive-properties: true
      deserialization:
         accept-single-value-as-array: true
         fail-on-unknown-properties: true
      serialization:
         write-empty-json-arrays: false
         fail-on-empty-beans: false
logging:
   config: "classpath:logback-spring.xml"

no.nav.security.jwt:
   issuer:
      azuread:
         discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
         accepted_audience: ${AZURE_APP_CLIENT_ID}
   client:
      registration:
         familie-oppdrag:
            resource-url: ${FAMILIE_OPPDRAG_API_URL}
            token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
            grant-type: client_credentials
            scope: ${FAMILIE_OPPDRAG_SCOPE}
            authentication:
               client-id: ${AZURE_APP_CLIENT_ID}
               client-secret: ${AZURE_APP_CLIENT_SECRET}
               client-auth-method: client_secret_basic
         familie-dokarkiv:
            resource-url: ${FAMILIE_INTEGRASJONER_API_URL}
            token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
            grant-type: client_credentials
            scope: ${FAMILIE_INTEGRASJONER_SCOPE}
            authentication:
               client-id: ${AZURE_APP_CLIENT_ID}
               client-secret: ${AZURE_APP_CLIENT_SECRET}
               client-auth-method: client_secret_basic
         infotrygd-feed:
            resource-url: ${INFOTRYGD_FEED_API_URL}
            token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
            grant-type: client_credentials
            scope: ${EF_INFOTRYGD_FEED_SCOPE}
            authentication:
               client-id: ${AZURE_APP_CLIENT_ID}
               client-secret: ${AZURE_APP_CLIENT_SECRET}
               client-auth-method: client_secret_basic

management:
   endpoint.health.show-details: always
   endpoints.web:
      exposure.include: info, health, metrics, prometheus, mappings
      base-path: "/internal"
      path-mapping:
         info: "isAlive"

arena-mq:
   queueManager: MPLS01
   channel: P_FAMILIE_EF_IVERKS
   hostname: a01apvl247.adeo.no
   port: 1414
   queueName: QA.P_475.SOB_VEDTAKHENDELSER_ARE
   servicebruker: ${SERVICEBRUKER}
   servicebrukerPassord: ${SERVICEBRUKER_PASSORD}

funksjonsbrytere:
   enabled: true
   unleash:
      uri: https://unleash.nais.io/api/
      environment: ${NAIS_CLUSTER_NAME}
      applicationName: ${NAIS_APP_NAME}

FAMILIE_OPPDRAG_API_URL: https://familie-oppdrag.prod-fss-pub.nais.io
ENSLIG_FORSORGER_VEDTAK_TOPIC: teamfamilie.aapen-ensligforsorger-vedtak-v1
ENSLIG_FORSORGER_BEHANDLING_TOPIC: teamfamilie.aapen-ensligforsorger-behandling-test
FAMILIE_INTEGRASJONER_API_URL: https://familie-integrasjoner.prod-fss-pub.nais.io
INFOTRYGD_FEED_API_URL: https://familie-ef-infotrygd-feed.prod-fss-pub.nais.io

prosessering:
   fixedDelayString:
      in:
         milliseconds: 10000
   delete:
      after:
         weeks: 16