server:
   servlet:
      context-path: /
spring:
   flyway:
      enabled: true
   datasource:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/familie-ef-iverksett
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      hikari:
         maximum-pool-size: 5
         connection-test-query: "select 1"
         max-lifetime: 30000
         minimum-idle: 1
   application:
      name: iverksett
   jackson:
      mapper:
         accept-case-insensitive-properties: true
      deserialization:
         accept-single-value-as-array: true
         fail-on-unknown-properties: true
      serialization:
         write-empty-json-arrays: false
         fail-on-empty-beans: false
logging:
   config: "classpath:logback-spring.xml"
no.nav.security.jwt:
   issuer:
      aad:
         discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
         accepted_audience: ${AZURE_APP_CLIENT_ID}

management:
   endpoint.health.show-details: always
   endpoints.web:
      exposure.include: info, health, metrics, prometheus
      base-path: "/internal"
      path-mapping:
         info: "isAlive"
