server:
   servlet:
      context-path: /
spring:
   application:
      name: iverksett
   jackson:
      mapper:
         accept-case-insensitive-properties: true
      deserialization:
         accept-single-value-as-array: true
         fail-on-unknown-properties: true
      serialization:
         write-empty-json-arrays: false
         fail-on-empty-beans: false

no.nav.security.jwt:
   issuer:
      aad:
         discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
         accepted_audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always
