arena-mq:
  queueManager: MQLS01
  channel: Q1_FAMILIE_EF_IVERKS
  hostname: b27apvl219.preprod.local
  port: 1413
  queueName: QA.Q1_ARENA.VEDTAKHENDELSER_EF

spring:
  datasource:
    url: ${DB_JDBC_URL}
    hikari:
      maximum-pool-size: 5
      connection-test-query: "select 1"
      max-lifetime: 900000
      minimum-idle: 1
      data-source-properties:
        ssl: true
        sslmode: ${DB_SSLMODE}
        sslcert: ${DB_SSLCERT}
        sslkey: ${DB_SSLKEY_PK8}
        sslrootcert: ${DB_SSLROOTCERT}

DEPLOY_ENV: dev
ENSLIG_FORSORGER_VEDTAK_TOPIC: teamfamilie.aapen-ensligforsorger-vedtak-test
ENSLIG_FORSORGER_BEHANDLING_TOPIC: teamfamilie.aapen-ensligforsorger-behandling-test
prosessering.rolle: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS 928636f4-fd0d-4149-978e-a6fb68bb19de

TEAMFAMILIE_SAKSBEHANDLER_GROUP_ID: "ee5e0b5e-454c-4612-b931-1fe363df7c2c" # 0000-GA-Enslig-Forsorger-Saksbehandler
TEAMFAMILIE_BESLUTTER_GROUP_ID: "01166863-22f1-4e16-9785-d7a05a22df74" # 0000-GA-Enslig-Forsorger-Beslutter

TILBAKEKREVING_REQUEST_TOPIC:
