apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-ef-overgangstonad-v1
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 1440
  acl:
    - team: teamfamilie
      application: familie-ef-iverksett
      access: read
    - team: teamfamilie
      application: familie-baks-mottak
      access: read
    - team: teamfamilie
      application: infotrygd-goldengate
      access: write