apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-iverksett
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: "{{ image }}"
  ingresses:
    - https://familie-ef-iverksett.intern.dev.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: false
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 50m
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  envFrom:
    - secret: familie-ef-iverksett
    - secret: familie-ef-iverksett-unleash-api-token
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de"  # 0000-GA-STDAPPS gir tilgang til prosessering
          - id: "87190cf3-b278-457d-8ab7-1a5c55a9edd7" # Group_87190cf3-b278-457d-8ab7-1a5c55a9edd7 gir tilgang til prosessering
          - id: "6406aba2-b930-41d3-a85b-dd13731bc974" # 0000-GA-Enslig-Forsorger-Saksbehandler
          - id: "5fcc0e1d-a4c2-49f0-93dc-27c9fea41e54" # 0000-GA-Enslig-Forsorger-Beslutter
        extra:
          - "NAVident"
          - "azp_name"
      replyURLs:
        - https://familie-ef-iverksett.intern.dev.nav.no/swagger-ui/oauth2-redirect.html
      singlePageApplication: true
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak
        - application: familie-ef-sak-lokal
        - application: familie-prosessering
        - application: familie-ef-e2e
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
        - application: etterlatte-prosessering
          namespace: etterlatte
    outbound:
      rules:
        - application: tilbakekreving-backend
          namespace: tilbake
        - application: logging
          namespace: nais-system
      external:
        - host: b27apvl219.preprod.local
          ports:
            - port: 1413
        - host: familie-oppdrag.dev-fss-pub.nais.io
        - host: familie-ef-infotrygd-feed.dev-fss-pub.nais.io
        - host: teamfamilie-unleash-api.nav.cloud.nais.io
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        name: familie-ef-iverksett-17
        tier: db-f1-micro
        diskAutoresize: true
        cascadingDelete: false
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: familie-ef-iverksett
            envVarPrefix: DB
  kafka:
    pool: nav-dev
