apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-iverksett
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  ingresses:
    - https://familie-ef-iverksett.intern.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: 1500m
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  envFrom:
    - secret: familie
    - secret: familie-ef-iverksett
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "87190cf3-b278-457d-8ab7-1a5c55a9edd7" # Group_87190cf3-b278-457d-8ab7-1a5c55a9edd7 gir tilgang til prosessering
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak
        - application: familie-prosessering
    outbound:
      external:
        - host: familie-oppdrag.prod-fss-pub.nais.io
        - host: familie-ef-infotrygd-feed.prod-fss-pub.nais.io
  gcp:
    sqlInstances:
      - type: POSTGRES_12 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        databases:
          - name: familie-ef-iverksett
            envVarPrefix: DB
            diskAutoresize: true
            tier: db-g1-small
            cascadingDelete: false