apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-iverksett
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  ingresses:
    - https://familie-ef-iverksett.dev.intern.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: false
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: 1500m
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  envFrom:
    - secret: familie
    - secret: familie-ef-iverksett
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de"  # 0000-GA-STDAPPS gir tilgang til prosessering
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak
        - application: familie-ef-sak-lokal
        - application: familie-prosessering
    outbound:
      external:
        - host: familie-oppdrag.dev-fss-pub.nais.io
        - host: familie-ef-infotrygd-feed.dev-fss-pub.nais.io
  gcp:
    sqlInstances:
      - type: POSTGRES_12 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        cascadingDelete: false
        databases:
          - name: familie-ef-iverksett
            envVarPrefix: DB
  kafka:
    pool: nav-dev