apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-iverksett
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: "{{ image }}"
  ingresses:
    - https://familie-ef-iverksett.intern.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 0 # TODO: Settes tilbake til: 2
    max: 0 # TODO: Settes tilbake til: 4
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 100m
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  envFrom:
    - secret: familie-ef-iverksett
    - secret: familie-ef-iverksett-unleash-api-token
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "87190cf3-b278-457d-8ab7-1a5c55a9edd7" # Group_87190cf3-b278-457d-8ab7-1a5c55a9edd7 gir tilgang til prosessering
          - id: "6406aba2-b930-41d3-a85b-dd13731bc974" # 0000-GA-Enslig-Forsorger-Saksbehandler
          - id: "5fcc0e1d-a4c2-49f0-93dc-27c9fea41e54" # 0000-GA-Enslig-Forsorger-Beslutter
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak
        - application: familie-prosessering
    outbound:
      rules:
        - application: tilbakekreving-backend
          namespace: tilbake
      external:
        - host: mpls01.adeo.no
          ports:
            - port: 1414
        - host: familie-oppdrag.prod-fss-pub.nais.io
        - host: familie-ef-infotrygd-feed.prod-fss-pub.nais.io
        - host: teamfamilie-unleash-api.nav.cloud.nais.io
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        name: familie-ef-iverksett-17
        tier: db-custom-1-3840
        diskAutoresize: true
        cascadingDelete: false
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: familie-ef-iverksett
            envVarPrefix: DB
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "on"
          - name: "pgaudit.log"
            value: "write,ddl,role"
          - name: "pgaudit.log_parameter"
            value: "on"
  kafka:
    pool: nav-prod
