apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-ensligforsorger-vedtak-arbeidsoppfolging
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720
  acl:
    - team: teamfamilie
      application: familie-ef-iverksett
      access: readwrite
    - team: pto
      application: veilarbportefolje
      access: read