apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-ensligforsorger-vedtak-v1
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  pool: nav-prod
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720
  acl:
    - team: teamfamilie
      application: familie-ef-iverksett
      access: readwrite
    - team: dv-familie
      application: dvh-famef-konsumer
      access: read