ALTER TABLE iverksett
    ADD COLUMN opprettet_tid TIMESTAMP(3) NOT NULL DEFAULT LOCALTIMESTAMP;
ALTER TABLE brev
    ADD COLUMN opprettet_tid TIMESTAMP(3) NOT NULL DEFAULT LOCALTIMESTAMP;
ALTER TABLE behandlingsstatistikk
    ADD COLUMN opprettet_tid TIMESTAMP(3) NOT NULL DEFAULT LOCALTIMESTAMP;

ALTER TABLE iverksett_resultat
    ADD COLUMN opprettet_tid TIMESTAMP(3) NOT NULL DEFAULT LOCALTIMESTAMP;
ALTER TABLE iverksett_resultat
    ADD COLUMN endret_tid TIMESTAMP(3) NOT NULL DEFAULT LOCALTIMESTAMP;