name: Bygg pull request

on:
  pull_request:
  push:
    branches-ignore:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set cache key
        run: |
          echo 'CACHE_KEY=$(expr $(date +%V) - 1 + 1)' >> $GITHUB_ENV
          echo 'PREVIOUS_CACHE_KEY=$(expr $(date +%V) - 1)' >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ env.CACHE_KEY }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ env.PREVIOUS_CACHE_KEY }}
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build
        shell: bash
        run: |
          echo "Building $(echo $GITHUB_SHA | cut -c1-7)"
          mvn package --quiet --batch-mode --settings ./.m2/settings.xml -DtrimStackTrace=false -Dchangelist= -Dsha1=-$(date +%Y.%m.%d.%H%M%S)-$(echo $GITHUB_SHA | cut -c1-7)
        env:
          TZ: "Europe/Oslo"
